import { NextResponse } from "next/server";
import * as anthropicService from "@/services/ai/anthropicService";
import * as openaiService from "@/services/ai/openaiService";
import { AIError } from "@/services/ai/types";
import { transformFeedbackToInstructions } from "@/services/feedback/feedbackTransformer";
import type { Provider } from "@/types/chat";
import type { Screenplay } from "@/types/screenplay";
import type { Feedback } from "@/types/feedback";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type RequestBody = {
  provider?: unknown;
  feedback?: unknown;
  script?: unknown;
  instructions?: unknown;
};

function isProvider(v: unknown): v is Provider {
  return v === "claude" || v === "gpt";
}

export async function POST(req: Request) {
  let body: RequestBody;
  try {
    body = (await req.json()) as RequestBody;
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body.", code: "bad_request" },
      { status: 400 }
    );
  }

  const provider = body.provider;
  if (!isProvider(provider)) {
    return NextResponse.json(
      { error: "Provider must be 'claude' or 'gpt'.", code: "bad_request" },
      { status: 400 }
    );
  }

  const feedback = body.feedback as Feedback | null;
  const script = body.script as Screenplay | null;

  if (!feedback || !script) {
    return NextResponse.json(
      { error: "Missing feedback or script.", code: "bad_request" },
      { status: 400 }
    );
  }

  const projectInstructions =
    typeof body.instructions === "string" ? body.instructions : "";

  // ── Transform feedback notes into structured edit instructions ─────────
  const transformed = transformFeedbackToInstructions(feedback, script);

  console.info(
    `[apply-feedback] ${transformed.instructions.length} instructions, ` +
      `${transformed.elementIndex.length} elements, provider=${provider}`
  );

  // ── Call AI with the specialised apply-feedback prompt ─────────────────
  // We bypass the standard buildSystemPrompt entirely and use the one
  // generated by the transformer, which includes the numbered element index.
  const service = provider === "claude" ? anthropicService : openaiService;

  try {
    const result = await service.generate({
      prompt: transformed.userMessage,
      script,
      instructions: projectInstructions,
      // Pass the custom system prompt override so the services use it.
      _systemPromptOverride: transformed.systemPrompt,
    } as Parameters<typeof service.generate>[0]);

    console.info(
      `[apply-feedback] AI returned ${result.suggestions.length} raw suggestions`
    );

    return NextResponse.json({
      content: result.content,
      suggestions: result.suggestions,
      provider: result.provider,
    });
  } catch (err) {
    if (err instanceof AIError) {
      console.error("[apply-feedback] AIError:", err.code, err.message);
      return NextResponse.json(
        { error: err.message, code: err.code },
        { status: err.status }
      );
    }
    console.error("[apply-feedback] unexpected error:", err);
    const message =
      err instanceof Error ? err.message : "Unexpected server error.";
    return NextResponse.json(
      { error: message, code: "unknown" },
      { status: 500 }
    );
  }
}
